insert into locations values ('ab1','Edmonton','Alberta','UofA LRT st');
insert into locations values ('ab2','Edmonton','Alberta','WEM LRT Station');
insert into locations values ('ab3','Edmonton','Alberta','Ross Sheppard High School');
insert into locations values ('ab4','Edmonton','Alberta','Southgate LRT Station');
insert into locations values ('ab5','Edmonton','Alberta','White Avenue');
insert into locations values ('ab6','Edmonton','Alberta','Hawlewak Park');
insert into locations values ('ab7','Edmonton','Alberta','City Hall');
insert into locations values ('ab8','Edmonton','Alberta','Rogers Place');
insert into locations values ('ab9','Edmonton','Alberta','MacEwan LRT Station');
insert into locations values ('ab10','Edmonton','Alberta','Nait LRT Station');
insert into locations values ('ab11','Calgary','Alberta','Airport');
insert into locations values ('ab12','Calgary','Alberta','111 Edmonton Tr.');
insert into locations values ('ab13','Red Deer','Alberta','City Hall');
insert into locations values ('ab14','Red Deer','Alberta','Airport');
insert into locations values ('ab15','Sherwood Park','Alberta',null);
insert into locations values ('bc1','Vancouver','British Columbia','Stanley Park');
insert into locations values ('bc2','Vancouver','British Columbia','Airport');
insert into locations values ('sk1','Regina','Saskatchewan','University of Regina');
insert into locations values ('sk2','Saskatoon','Saskatchewan','City Hall');
insert into locations values ('nu1','Iqaluit','Nunavut',null);
